version: "3"
services:
  nfs-server:
    image: erichough/nfs-server
    restart: always
    container_name: nfs
    privileged: true
    network_mode: "host"
    ports:
      - 2049:2049
    environment: 
      NFS_EXPORT_0: '/export *(rw,fsid=0,sync,insecure,no_root_squash,no_subtree_check)'
      NFS_VERSION: 4.2
      NFS_DISABLE_VERSION_3: 1
      NFS_SERVER_THREAD_COUNT: 1
    volumes:
      - /mnt/nfs-storage:/export
      - /lib/modules:/lib/modules:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"