version: "3"
services:
  ganesha:
    image: figassis/nfs:0.0.5
    restart: always
    container_name: nfs
    privileged: true
    ports:
      - 2049:2049
    volumes:
      - /mnt/nfs-storage:/export
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"