version: "3"
services:
  localnfs:
    build: .
    # image: figassis/nfs:0.0.3
    restart: always
    container_name: local
    privileged: true
    ports:
      - 2049:2049
    volumes:
      - local:/export
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
volumes:
  local: